### ISSUE TITLE
Fix display issue with Presentation View.

### ISSUE THREAD

**Issue by JoshDunnDev** [digitalbazaar/bedrock-vue-credential-card#45]
Fix display issue with Presentation View. Close button is no longer in the correct location:

![Screen Shot 2021-09-13 at 11 19 03 AM](https://user-images.githubusercontent.com/22648574/133128351-cc65b779-60af-4318-87c6-335be8dc67cb.png)

**Comment by dmitrizagidulin** [comment]
Fixed in PR #46, closing.
